export const projects = [
  {
    title: 'LOUNGEZILLA',
    description: " Do you find yourself asking friends and family what tv shows or movies you should watch for the evening? Visit loungezilla and browse around or watch a trailer, add something to a collection.",
    image: '/images/loungezilla.png',
    tags: [ 'React', 'Rails', 'PostgreSQL', 'The-Movie-DB-API', ],
    source: 'https://loungezilla.herokuapp.com',
    visit: 'https://github.com/Jacobharv00/loungezilla',
    demo: 'https://www.loom.com/share/0d25d02abde4440db6cb4cb658a43364?sharedAppSource=personal_library',
    id: 0,
  },
  {
    title: 'E-Boss',
    description: "Have you been looking for a e-commerce store that sells the hottest and sleekest products? E-Boss is a e-commerce store where you can find everything you need to get your developer office all set up.",
    image: '/images/e-boss.png',
    tags: [ 'React', 'Commerce.js', 'Stripe.js', 'Material UI' ],
    source: 'https://eboss.netlify.app',
    visit: 'https://github.com/Jacobharv00/e-commerce',
    demo: 'https://eboss.netlify.app',
    id: 1,
  },
  {
    title: 'Movie Lounge',
    description: "Not sure what movie to watch? Visit movie-lounge and start searching for movies. Add to your watch list so you can know what movie to watch for movie night! And once you watched something give it a thumbs up or down to let others know how it was.",
    image: '/images/movie-lounge.png',
    tags: [ 'React', 'JSON', 'The-Movie-DB-API', 'Material UI' ],
    source: 'https://movie-lounge.netlify.app',
    visit: 'https://github.com/Jacobharv00/movie-lounge',
    demo: 'https://www.loom.com/share/1d88bc16afe942bcb15302fdc1bfbcca?sharedAppSource=personal_library',
    id: 2,
  },
  {
    title: 'Crypto Cookie',
    description: "Looking to trade crypto? This is a Web 3.0 application that allows users to trade ethereum through the blockchain using metamask as a wallet. You can connect your metamask wallet and trade crypto with different accounts. Web 3.0 is the future!",
    image: '/images/cryptocookie.png',
    tags: [ 'React', 'Solidity', 'Ethers.js', 'Alchemy', 'Tailwind' ],
    source: 'https://cryptocookie.netlify.app',
    visit: 'https://github.com/Jacobharv00/crypto-cookie',
    demo: 'https://cryptocookie.netlify.app',
    id: 3,
  },
]

export const TimeLineData = [
  { year: 2020, text: 'Started learning how to program by taking a Udemy JavaScript Course everyday after work.', },
  { year: 2021, text: 'Built my first todo application and hangman game, and deployed them both live for anyone in the world to use.', },
  { year: 2021, text: 'Accepted into Flatiron School for Full Stack Software Engineering program.', },
  { year: 2021, text: 'Flatiron School: Learned a variety of programming languages and techniques for building full stack applications, and built projects with a new partner every three weeks.' },
  { year: 2021, text: 'Graduated Flatiron School with 5 completed projects, two of which are Full Stack applications, and an even greater love for coding and solving problems.' },
  { year: 2021, text: 'After graduation I now am continuing to learn everyday by building new projects, studying up on core JavaScript and Rails skills, practicing data structures & algorithms, learning automated testing & TDD, and in my free time I listen to podcasts on computer science topics.' },
]